name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/lightsail_key
        chmod 600 ~/.ssh/lightsail_key
        ssh-keyscan -H ${{ secrets.LIGHTSAIL_SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to AWS Lightsail
      run: |
        ssh -i ~/.ssh/lightsail_key -p ${{ secrets.LIGHTSAIL_SSH_PORT }} ${{ secrets.LIGHTSAIL_SSH_USER }}@${{ secrets.LIGHTSAIL_SSH_HOST }} << 'EOF'
          cd /www/wwwroot/lareef.publicvm.com
          git pull origin main
          # Add any other commands to build or restart your application
        EOF
